MyTown/config/routes.rb
MyTown::Application.routes.draw do
  resources :attractions

  resources :towns

end

MyTown/app/models/attraction.rb
class Attraction < ActiveRecord::Base
	belongs_to :town
	scope :alphabetical,  -> { order(:name) }

	before_validation :find_attraction_coordinates, :if => :street_changed?
	private
	def find_attraction_coordinates
    coord = Geocoder.coordinates("#{street}, #{town.name}, #{town.state}")
    if coord
      self.latitude = coord[0]
      self.longitude = coord[1]
    else 
      errors.add(:base, "Error with geocoding")
    end
    coord
  end
end

MyTown/app/models/town.rb
class Town < ActiveRecord::Base
	has_many :attractions, dependent: :destroy

	before_validation :find_town_coordinates
	STATES_LIST = [['Alabama', 'AL'],['Alaska', 'AK'],['Arizona', 'AZ'],['Arkansas', 'AR'],['California', 'CA'],['Colorado', 'CO'],['Connectict', 'CT'],['Delaware', 'DE'],['District of Columbia ', 'DC'],['Florida', 'FL'],['Georgia', 'GA'],['Hawaii', 'HI'],['Idaho', 'ID'],['Illinois', 'IL'],['Indiana', 'IN'],['Iowa', 'IA'],['Kansas', 'KS'],['Kentucky', 'KY'],['Louisiana', 'LA'],['Maine', 'ME'],['Maryland', 'MD'],['Massachusetts', 'MA'],['Michigan', 'MI'],['Minnesota', 'MN'],['Mississippi', 'MS'],['Missouri', 'MO'],['Montana', 'MT'],['Nebraska', 'NE'],['Nevada', 'NV'],['New Hampshire', 'NH'],['New Jersey', 'NJ'],['New Mexico', 'NM'],['New York', 'NY'],['North Carolina','NC'],['North Dakota', 'ND'],['Ohio', 'OH'],['Oklahoma', 'OK'],['Oregon', 'OR'],['Pennsylvania', 'PA'],['Rhode Island', 'RI'],['South Carolina', 'SC'],['South Dakota', 'SD'],['Tennessee', 'TN'],['Texas', 'TX'],['Utah', 'UT'],['Vermont', 'VT'],['Virginia', 'VA'],['Washington', 'WA'],['West Virginia', 'WV'],['Wisconsin ', 'WI'],['Wyoming', 'WY']]
	scope :alphabetical,  -> { order(:name) }
	accepts_nested_attributes_for :attractions, reject_if: lambda { |attraction| attraction[:name].blank? }, allow_destroy: true
	 def create_map_link(zoom=12,width=800,height=800)

	 	markers = ""; i = 1
  		self.attractions.alphabetical.to_a.each do |attr|
    		markers += "&markers=color:red%7Ccolor:red%7Clabel:#{i}%7C#{attr.latitude},#{attr.longitude}"
    		i += 1
  		end
  		puts latitude, longitude
   		map = "http://maps.google.com/maps/api/staticmap?center= #{latitude},#{longitude}&zoom=#{zoom}&size=#{width}x#{height}&maptype=roadmap&#{markers}sensor=false"
  	end


	private
	def find_town_coordinates
    coord = Geocoder.coordinates("#{name}, #{state}")
    if coord
      self.latitude = coord[0]
      self.longitude = coord[1]
    else 
      errors.add(:base, "Error with geocoding")
    end
    coord
  end



end

MyTown/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MyTown/app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]

  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
  end

  # GET /attractions/1/edit
  def edit
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = Attraction.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attraction }
      else
        format.html { render action: 'new' }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:name, :street, :town_id, :latitude, :longitude)
    end
end

MyTown/app/controllers/towns_controller.rb
class TownsController < ApplicationController
  before_action :set_town, only: [:show, :edit, :update, :destroy]

  # GET /towns
  # GET /towns.json
  def index
    @towns = Town.all
  end

  # GET /towns/1
  # GET /towns/1.json
  def show
    @attractions = @town.attractions.alphabetical.to_a
  end

  # GET /towns/new
  def new
    @town = Town.new
    @town.attractions.build
  end

  # GET /towns/1/edit
  def edit
  end

  # POST /towns
  # POST /towns.json
  def create
    @town = Town.new(town_params)

    respond_to do |format|
      if @town.save
        format.html { redirect_to @town, notice: 'Town was successfully created.' }
        format.json { render action: 'show', status: :created, location: @town }
      else
        format.html { render action: 'new' }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /towns/1
  # PATCH/PUT /towns/1.json
  def update
    respond_to do |format|
      if @town.update(town_params)
        format.html { redirect_to @town, notice: 'Town was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1
  # DELETE /towns/1.json
  def destroy
    @town.destroy
    respond_to do |format|
      format.html { redirect_to towns_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_town
      @town = Town.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def town_params
      params.require(:town).permit(:name, :state, :description, attractions_attributes: [:id, :name, :street, :_destroy])
    end
end

MyTown/app/helpers/application_helper.rb
module ApplicationHelper
end

MyTown/app/helpers/attractions_helper.rb
module AttractionsHelper
end

MyTown/app/helpers/towns_helper.rb
module TownsHelper
end

MyTown/app/views/attractions/_form.html.erb
<%= form_for(@attraction) do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :town_id %><br>
    <%= f.number_field :town_id %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MyTown/app/views/attractions/edit.html.erb
<h1>Editing attraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

MyTown/app/views/attractions/index.html.erb
<h1>Listing attractions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>Town</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>
        <td><%= attraction.name %></td>
        <td><%= attraction.street %></td>
        <td><%= attraction.town_id %></td>
        <td><%= attraction.latitude %></td>
        <td><%= attraction.longitude %></td>
        <td><%= link_to 'Show', attraction %></td>
        <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
        <td><%= link_to 'Destroy', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attraction', new_attraction_path %>

MyTown/app/views/attractions/new.html.erb
<h1>New attraction</h1>

<%= render 'form' %>

<%= link_to 'Back', attractions_path %>

MyTown/app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attraction.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @attraction.street %>
</p>

<p>
  <strong>Town:</strong>
  <%= @attraction.town_id %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @attraction.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @attraction.longitude %>
</p>

<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>

MyTown/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyTown</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MyTown/app/views/partials/_attraction_fields.html.erb
<div class="fields">
    <div class="min_attraction">
      <!-- x icon to remove -->
      <%= f.link_to_remove("x") %>
      <!-- fields -->
      <%= f.input :name %>
      <%= f.input :street %>
    </div>
  </div>

MyTown/app/views/towns/_attraction_fields.html.erb
<div class="fields">
    <div class="min_attraction">
      <!-- x icon to remove -->
      <%= f.link_to_remove("x") %>
      <!-- fields -->
      <%= f.input :name %>
      <%= f.input :street %>
    </div>
  </div>

MyTown/app/views/towns/_form.html.erb
 <%= simple_nested_form_for @town, :html => { :class => 'form-horizontal' } do |town_form| %>
    <div class="row">
      <div class="span7">
        <fieldset>
          <legend><%= controller.action_name.capitalize %> Town</legend>
          <%= render :partial => "town_fields", :locals => { :f => town_form } %>
        </fieldset>
      </div>

    <div class="span5">
      <legend>Attractions for this town</legend>
        <div id="town_attractions">
          <%= town_form.simple_fields_for :attractions do |attraction_form| %>
            <%= render :partial => "attraction_fields", :locals => { :f => attraction_form } %>
          <% end %> 
          <p>
            <br /><%= town_form.link_to_add("Add Attraction", :attractions, :class => 'button tiny') %>
          </p>
        </div> 
      </div>
    </div>
    <div class="form-actions">
      <%= town_form.submit nil, :class => 'button radius' %>
      <%= link_to 'Cancel', towns_path, :class => 'button secondary' %>
    </div>
  <% end %>

MyTown/app/views/towns/_town_fields.html.erb
 <%= f.input :name %>
  <%= f.input :state, :collection => Town::STATES_LIST, :include_blank => true %>
  <%= f.input :description, :input_html => { :rows => 4 } %>

MyTown/app/views/towns/edit.html.erb
<h1>Editing town</h1>

<%= render 'form' %>

<%= link_to 'Show', @town %> |
<%= link_to 'Back', towns_path %>

MyTown/app/views/towns/index.html.erb
<h1>Listing towns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th>Description</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @towns.each do |town| %>
      <tr>
        <td><%= town.name %></td>
        <td><%= town.state %></td>
        <td><%= town.description %></td>
        <td><%= town.latitude %></td>
        <td><%= town.longitude %></td>
        <td><%= link_to 'Show', town %></td>
        <td><%= link_to 'Edit', edit_town_path(town) %></td>
        <td><%= link_to 'Destroy', town, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Town', new_town_path %>

MyTown/app/views/towns/new.html.erb
<h1>New town</h1>

<%= render 'form' %>

<%= link_to 'Back', towns_path %>

MyTown/app/views/towns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @town.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @town.state %>
</p>

<p>
  <strong>Description:</strong>
  <%= @town.description %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @town.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @town.longitude %>
</p>

<p>
  <b>Attractions in <%= @town.name %>:</b>
    <ol>
      <% for attraction in @attractions %>
        <li><%= attraction.name %> - <%= attraction.street %></li>
      <% end %>
    </ol>
    <%= image_tag @town.create_map_link %>
  </p>
<%= link_to 'Edit', edit_town_path(@town) %> |
<%= link_to 'Back', towns_path %>